### ISSUE TITLE
Steam path not found - wrong path

### ISSUE THREAD

**Issue by supertin** [PaulCombal/SamRewritten-legacy#1]
SamRewritten couldn't find my Steam install (clean install done about 7 days ago on a clean Ubuntu 18.10 done the same day).

In "MySteam.cpp", it looks for "/.steam/appcache/appinfo.vdf", but the correct path in my install is "/.steam/steam/appcache/appinfo.vdf". The resulting returned string also needs the additional "/steam" too (**return std::string(home_path + "/.steam/steam");**)

Works fine after doing that (slightly confusing UI, but so is the original if I recall).

**Comment by PaulCombal** [comment]
Alright, my latest commit should fix this, but I was unable to replicate the issue. If you could try again and tell me if it works, that'd be awesome :)
Thanks for the input!

**Comment by supertin** [comment]
Works great. :smile:
