### ISSUE TITLE
provide overview of how this thing works

### ISSUE THREAD

**Issue by vapier** [PaulCombal/SamRewritten-legacy#105]
could you put a section in the readme explaining how this thing works ?  i have theories, but i've never programmed the Steam SDK before, so i don't know if i'm completely off base.

what i think is happening:
* Steam's SDK exposes APIs for managing achievements
* That API is defined in the `libsteam_api.so` file
* `libsteam_api.so` talks to a running Steam instance to process its requests
* SAM makes calls to `libsteam_api.so` to look up games, their achievements, make changes, etc...

**Comment by PaulCombal** [comment]
I'm not sure the README is the right place for this. What do you think is best: a Github Wiki or another markdown file for technical documentation? That's something I can do when I have a bit of time. I haven't touched this thing in years so I couldn't tell you how everything works right now off the top of my head  😬

Great idea, if that can motivate more people to contribute that's great!

**Comment by vapier** [comment]
wiki is fine. wherever works best.

**Comment by PaulCombal** [comment]
Alright, I'll definitely do this when I have some time. I'll let you know!

**Comment by PaulCombal** [comment]
Hey, I took my sweet time, but can you please have a look at this and tell me what you think?

https://github.com/PaulCombal/SamRewritten/blob/dev/doc/OVERVIEW.md

I would really appreciate it :)

**Comment by PaulCombal** [comment]
I think the last PR covers it. Thank you for contributing, feel free to suggest anything else!
