### ISSUE TITLE
Can you unlock protected achievements?

### ISSUE THREAD

**Issue by jhordirs** [PaulCombal/SamRewritten-legacy#113]
Hello, there are some games on SAM that you can't unlock saying that they're protected or server side achievements and appear in color red. Can you unlock those achievements with this program? Thanks in advance.
![93773873-ec060200-fc63-11ea-8f09-0ff1d9609ded](https://user-images.githubusercontent.com/51026386/147837994-34101325-a286-4fdb-938a-689d1f8f53d7.png)
(this error message is from SAM)

**Comment by PaulCombal** [comment]
I don't know much about these "protected achievements". Right now SamRewritten doesn't make a difference for them. If SAM can't unlock them, there's a lot to bet that SamRewritten won't either, as they use the same mechanisms to lock and unlock achievements.

If anyone has more information about these achievements, sharing it would greatly help us!

**Comment by jhordirs** [comment]
Yup, can confirm it doesn't work, even if you attempt to do it (nothing happens). Worth a try i guess, damn achievements that you can't unlock because game servers are no longer avaliable / removed from steam.
![Screenshot_1](https://user-images.githubusercontent.com/51026386/147859255-ae128551-106b-443d-9406-3790cea9ce3f.png)
It is really weird because I had a couple of achievements and I, somehow, managed to locked/reset them (with SAM) and it worked (the error messaged popped, however, changes are reflected on Steam) , so I don't understand how can you lock and not unlock them.

**Comment by PaulCombal** [comment]
Odd indeed, though the locking function of Steamworks is intended for testing only so it may bypass a few checks. 
Unfortunately this is as far as it can get with my knowledge.. If you learn anything new about this please let me know, but in the meantime I will have to close the thread if there is not more activity. Thanks for reporting!
