### ISSUE TITLE
Crash:  premature EOF

### ISSUE THREAD

**Issue by fbievan** [PaulCombal/SamRewritten-legacy#120]
Simple crash
```
Parsing error: parse error: premature EOF
                                       {"applist":{"apps":[{"appid":22
                     (right here) ------^
```

**Comment by PaulCombal** [comment]
Very weird.. can you try the fix I suggested in #114 and tell me if it changes anything? Is your internet connection stable?

**Comment by fbievan** [comment]
No, my connection was not stable at all, yesterday. Works completely fine, today. Any reason why it didn't yesterday? Even with my connection being not stable, i would expect it to still pull from wherever it needed to

**Comment by PaulCombal** [comment]
Strange, I don't know what could have happened. Maybe you lost connection while downloading the file, I don't know. Glad it works in the end. I have referenced this issue in the possible enhancements list.

Thanks for reporting the issue, feel free to close it if there is nothing else

**Comment by fbievan** [comment]
Appreciate this work.
