### ISSUE TITLE
Some games don't show up

### ISSUE THREAD

**Issue by everlyy** [PaulCombal/SamRewritten-legacy#123]
Trying to modify my achievements for "Miss Neko 2", but the game doesn't show up in the manager.
Game url: https://store.steampowered.com/app/1203420/Miss_Neko_2/

**Comment by PaulCombal** [comment]
Does entering the AppID in the search bar? Any new report from #92 ?

**Comment by everlyy** [comment]
> Does entering the AppID in the search bar? Any new report from #92 ?

This worked, thanks!
