### ISSUE TITLE
Add Steam stats

### ISSUE THREAD

**Issue by ghost** [PaulCombal/SamRewritten-legacy#13]
Main advantage original SAM, this unlock algorithm. It doesn’t just unlock, he emulating game process. 
For example when you unlock RANK achievement with original SAM in Dead by Daylight, you gets this RANK in game or achievements for kills in Insurgency, you gets it kill count in game.

**Comment by PaulCombal** [comment]
Yes, original SAM lets you edit stats as well, this is something currently not possible with SamRewritten, but will definitely be a feature for a future release!

**Comment by wgpierce** [comment]
If anyone would like to implement this on the dev branch, it'd be appreciated!
Otherwise I'll probably get to it in the next week or two.

**Comment by PaulCombal** [comment]
Wow you'e on a roll! Isn't it quite a lot of work? I mean doing the GUI and all seems pretty huge, as well as thinking of a good way to make it snappy to the user regarding loading.. Shouldn't we release first?

**Comment by wgpierce** [comment]
Well RIP the original requester, but if anyone wants to try out this feature, have a look at https://github.com/PaulCombal/SamRewritten/pull/54
