### ISSUE TITLE
Steam Deck makepkg error 1

### ISSUE THREAD

**Issue by Mudgie0205** [PaulCombal/SamRewritten-legacy#133]
So I've been trying to build on Arch with the AUR and have so far sorted a fakeroot issue but now I'm at a dead end. Also noob. Thanks

(deck@MudgieSteamDeck samrewritten-git)$ makepkg
==> Making package: samrewritten-git r236.3e8d088-1 (Tue 09 Aug 2022 11:39:30 AM IST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning SamRewritten git repo...
Cloning into bare repository '/home/deck/Desktop/samrewritten-git/SamRewritten'...
remote: Enumerating objects: 2123, done.
remote: Counting objects: 100% (185/185), done.
remote: Compressing objects: 100% (81/81), done.
remote: Total 2123 (delta 93), reused 163 (delta 91), pack-reused 1938
Receiving objects: 100% (2123/2123), 20.79 MiB | 5.30 MiB/s, done.
Resolving deltas: 100% (1465/1465), done.
==> Validating source files with sha256sums...
    SamRewritten ... Skipped
==> Extracting sources...
  -> Creating working copy of SamRewritten git repo...
Cloning into 'SamRewritten'...
done.
==> Starting pkgver()...
==> Updated version: samrewritten-git r243.6bf7002-1
==> Starting build()...
make: pkg-config: No such file or directory
make: pkg-config: No such file or directory
g++ -c -o obj/src/sockets/MyGameSocket.o src/sockets/MyGameSocket.cpp -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -std=c++17  -Wall
In file included from /usr/include/errno.h:28,
                 from /usr/include/c++/11.1.0/cerrno:42,
                 from /usr/include/c++/11.1.0/ext/string_conversions.h:44,
                 from /usr/include/c++/11.1.0/bits/basic_string.h:6594,
                 from /usr/include/c++/11.1.0/string:55,
                 from src/sockets/MySocket.h:3,
                 from src/sockets/MyServerSocket.h:2,
                 from src/sockets/MyGameSocket.h:2,
                 from src/sockets/MyGameSocket.cpp:3:
/usr/include/bits/errno.h:26:11: fatal error: linux/errno.h: No such file or directory
   26 | # include <linux/errno.h>
      |           ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:51: obj/src/sockets/MyGameSocket.o] Error 1
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by PaulCombal** [comment]
Do you have all the required packages installed? From what I see you're missing pkg-config and maybe the equivalent of linux-libc-dev for arch. If I had to guess this looks like a configuration issue on your end or you're not running a classic linux distro.

I guess SteamDeck is just a thing on its own. Do the AppImages work?

**Comment by Mudgie0205** [comment]
> Do you have all the required packages installed? From what I see you're missing pkg-config and maybe the equivalent of linux-libc-dev for arch. If I had to guess this looks like a configuration issue on your end or you're not running a classic linux distro.
> 
> 
> 
> I guess SteamDeck is just a thing on its own. Do the AppImages work?

I tried removing and reinstalling the prerequisites. Even pkg-config (most recent thing I noticed in the scenario).

Not sure how to use the AppImages but will have a try

**Comment by Mudgie0205** [comment]
Right I've sorted it. I just found where the #include <.sh> headers are and I did sudo pacman -S and installed the prerequisites for each header. After about 10 of them, it all worked :P
