### ISSUE TITLE
Icon concept

### ISSUE THREAD

**Issue by ghost** [PaulCombal/SamRewritten-legacy#14]
I drew an icon, how about using it.

![icon](https://i.ibb.co/2M1JVWR/Sam-Rewritten.png)

**Comment by ghost** [comment]
How it view on my panel.
![panel](https://i.ibb.co/b6PHffB/Screenshot-from-2019-09-28-14-08-50.png)

**Comment by PaulCombal** [comment]
Waow super cool! This looks great! I'm really busy right now, but we'll make sure to include it in a future release, but it may take some time since the tool is already in a big rewriting. What do you think @wgpierce ?

**Comment by wgpierce** [comment]
Looks great! If you make a pull request, we'll accept right away. Or I can add the icon when I can get to it. We can take the pull request in master since there haven't been any changes to the GUI yet.
