### ISSUE TITLE
doesn't launch - debian 11

### ISSUE THREAD

**Issue by okfruit** [PaulCombal/SamRewritten-legacy#145]
uuu@ldeb11:~/Desktop$ chmod +x SamRewritten-Ubuntu_18.04--d29ad13-x86_64.AppImage
uuu@ldeb11:~/Desktop$ ./SamRewritten-Ubuntu_18.04--d29ad13-x86_64.AppImage
/tmp/.mount_SamRewPFaICL/AppRun: line 5: warning: setlocale: LC_NUMERIC: cannot change locale (en_US.UTF-8): No such file or directory

(process:5345): Gtk-WARNING **: 13:11:52.904: Locale not supported by C library.
	Using the fallback 'C' locale.

(samrewritten:5345): Gtk-WARNING **: 13:11:53.292: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /home/uuu/.icons/Papirus-Dark/16x16/actions/image-missing.svg: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_font_options_get_variations (gdk-pixbuf-error-quark, 5)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /home/uuu/.icons/Papirus-Dark/16x16/actions/image-missing.svg: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_font_options_get_variations (gdk-pixbuf-error-quark, 5)
/tmp/.mount_SamRewPFaICL/AppRun: line 8:  5345 Aborted                 ${SCRIPT_PATH}/samrewritten $@

syslog: 
Dec 12 13:22:02 ldeb11 systemd[890]: tmp-.mount_SamRewSg2n09.mount: Succeeded.
Dec 12 13:22:02 ldeb11 systemd[1]: tmp-.mount_SamRewSg2n09.mount: Succeeded.

**Comment by PaulCombal** [comment]
Duplicate of #91?

Still waiting for package managers to make new build, yes, I'm planning a fix. Please close if it is indeed a duplicate.

**Comment by okfruit** [comment]
this solves the problem:
https://github.com/PaulCombal/SamRewritten/issues/91#issuecomment-789197974  

sorry.
