### ISSUE TITLE
SamRewritten doesnt start [Ubuntu 22.04]

### ISSUE THREAD

**Issue by tskxz** [PaulCombal/SamRewritten-legacy#153]
When i try to open it, nothing happens. I have this checked.
![image](https://github.com/PaulCombal/SamRewritten/assets/47666341/6522c8fb-c2a7-4b5f-b9d8-44cfbcc6422e)

I tried to run in command line too with
```
./SamRewritten-Ubuntu_18.04--d29ad13-x86_64.AppImage 
```

I got the following output
```
/tmp/.mount_SamRewwAbHbC/usr/bin/samrewritten: symbol lookup error: /lib/x86_64-linux-gnu/libgio-2.0.so.0: undefined symbol: g_module_open_full
```

**Comment by thrailkillr** [comment]
https://github.com/project-slippi/Ishiiruka/issues/323#issuecomment-977415376

**Comment by thrailkillr** [comment]
https://github.com/AppImage/AppImageKit/releases

**Comment by PaulCombal** [comment]
Does it work with this build? https://github.com/PaulCombal/SamRewritten/actions/runs/5049787125

**Comment by thrailkillr** [comment]
> Does it work with this build? https://github.com/PaulCombal/SamRewritten/actions/runs/5049787125

Should, basically the old ubuntu 18.04 images don't have working binaries, and that link to a comment deleted the outdated binaries so your system fills in the gaps with your updated ones.

**Comment by qurious-pixel** [comment]
The new builds that are produced with the PRs account for the updated symbol names in `libgio-2.0.so.0`

Please comment if they are not working as expected. 
The one from https://github.com/PaulCombal/SamRewritten/issues/153#issuecomment-1557944908

**Comment by tskxz** [comment]
I dont have ubuntu anymore, so i will close the issue as not planned
