### ISSUE TITLE
Doesn't start on Linux Mint 21.2

### ISSUE THREAD

**Issue by ErFuyl** [PaulCombal/SamRewritten-legacy#161]
Program Version: 2.1
OS: Linux Mint 21.2 CInnamon
Problem: Program doesn't start, starting on terminal gives the following output:
```
/tmp/.mount_SamRewWXRqnk/usr/bin/samrewritten: symbol lookup error: /lib/x86_64-linux-gnu/libgio-2.0.so.0: undefined symbol: g_module_open_full
``` 
i've tried older versions too, but all of them gives the same error.

**Comment by PaulCombal** [comment]
Have you tried to build it yourself?

**Comment by ErFuyl** [comment]
> Have you tried to build it yourself?

Compiled from source and ran launch.sh, it's working now. thanks!

**Comment by PaulCombal** [comment]
I'm glad you could find a solution :)

Sorry for the low maintenance of the project, I might get back to it one day!
