### ISSUE TITLE
_

### ISSUE THREAD

**Issue by cristoferluch** [PaulCombal/SamRewritten-legacy#162]

**Comment by PaulCombal** [comment]
Hi,

So far there is no known feature or workaround that I know of that would allow to do this.. You can always relock and unlock again an achievement to show the current date, but the API doesn't allow to set an unlocking date as far as I know.

**Comment by cristoferluch** [comment]
thanks

**Comment by cristoferluch** [comment]
Hello, 

I apologize for any inconvenience caused. Could you kindly consider removing this issue? 

Thank you for your attention.

**Comment by PaulCombal** [comment]
You don't need to apologize! It's natural to be curious and ask questions :)

My pleasure, have a good day

**Comment by cristoferluch** [comment]
Ok, Thank you
