### ISSUE TITLE
Please fix the app

### ISSUE THREAD

**Issue by Twig6943** [PaulCombal/SamRewritten-legacy#164]
The current AppImage is broken please do one of these things.
(By broken I mean it gives an error related to the libgio-2.0 on every machine I've tried this on. Mentioned issue can be found here https://github.com/PaulCombal/SamRewritten/issues/100 )
A.Fix the AppImage
B.Package the Application as a .deb package
C.Package the Application as a flatpak

I'm thinking of uploading the binaries to my profile if none of the said solutions are done.

**Comment by PaulCombal** [comment]
Ok, do it. Just make sure to respect the License.
