### ISSUE TITLE
samrewritten doesn't open

### ISSUE THREAD

**Issue by madmaxgrey** [PaulCombal/SamRewritten-legacy#167]
do you have any recent appimages that do work OOTB, as the one on your releases page is borked. im starting to feel like you created this to improve on SAM but no longer maintaining it. i just want to be able to use this on linux

**Comment by PaulCombal** [comment]
Hello, as I said on the pinned issue, I no longer have time to work on this project. I would recommend building the app yourself, it's very easy and can be done in a few commands, even to make an appimage!

As always contributions are welcome

**Comment by RoosterBurger** [comment]
Hi use my version, in some distros libgio-2.0.so.0 is not working. I removed this library and now it works perfect for me.
[SamRewritten-x86_64.AppImage.zip](https://github.com/PaulCombal/SamRewritten/files/15399948/SamRewritten-x86_64.AppImage.zip)
