### ISSUE TITLE
Issue running provided AppImage 

### ISSUE THREAD

**Issue by Cipher66hz** [PaulCombal/SamRewritten-legacy#173]
So I was able to run it when I compiled from source, but would prefer to use an appimage so that everything is contained in one file.
Im new to compiling AppImages from source, and had some problems making my own, so I opted to use the provided AppImage.

When attempting to run it, I'm receiving the following error:
```
./SamRewritten-Ubuntu_18.04--d29ad13-x86_64.AppImage
/tmp/.mount_SamRewznnzVD/usr/bin/samrewritten: symbol lookup error: /lib/x86_64-linux-gnu/libgio-2.0.so.0: undefined symbol: g_module_open_full
```
Im fine just running it via ```launch.sh``` from the source directory, but would prefer one self-contained appimage.

Any guidance would be highly appreciated. Thank you!

**Comment by PaulCombal** [comment]
Hello, 

Thank you for your interest in SamRewritten. This project is barely maintained and still has a lot of issues, and unfortunately  building and distributing the app is one of them.

I am aware that the AppImage is not working on most people's machines. If you have already built the application, you can follow what is said in the README to make your own AppImage:

To build your own AppImage, build SamRewritten normally, then execute build_appimage.sh from the package folder. A new AppImage will be generated with libraries from your system.

You should be able to then use that AppImage on all similar systems.

Does that answer your question?

**Comment by Cipher66hz** [comment]
Gosh, I wish I could offer to help maintain the project, but I'm not nearly at a level of programming to be able to contribute to a project like this.

I just saw that its possible to build my own AppImage through the README. Thank you for this :)

That does answer my question, thank you. 
I appreciate you porting this software over to GNU/Linux so that we too can take advantage of it; and I would like to say that the program works wonderfully. Excellent work <3

![Lain Dance](https://github.com/user-attachments/assets/d70dd0f9-2dcd-44f3-b7db-7b2a965893c2)
