### ISSUE TITLE
parse error: premature EOF

### ISSUE THREAD

**Issue by SebiTimeWaster** [PaulCombal/SamRewritten-legacy#177]
no matter if i run the released appimage, the tarball or compile the code myself, i always get this error on Ubuntu Cinnamon 24.10:

```
Parsing error: parse error: premature EOF
                                       
                     (right here) ------^
```

**Comment by PaulCombal** [comment]
Hi, are you connected to the internet?

**Comment by SebiTimeWaster** [comment]
yes, i am.

**Comment by SebiTimeWaster** [comment]
but anyway i dont know why that matters, it only tries to connect to localhost
![image](https://github.com/user-attachments/assets/366da7b7-269e-4013-8923-ff91328cee99)
and that port is open on my system
![image](https://github.com/user-attachments/assets/75c0bd8b-0bb9-4e4c-b54a-587d6b754313)

When i close Steam and run it, it complains about not being able to connect to steam, so that part seems to be working.

**Comment by PaulCombal** [comment]
Yeah my best bet is that it fails to download the game list, you can try to download it manually from there https://github.com/PaulCombal/SteamAppsListDumps/blob/master/game_achievements_list.json , then copy it to the temp directory of SAM (I think ~/.cache/SamRewritten).  Try to name it game_list.json in the folder too

**Comment by SebiTimeWaster** [comment]
i deleted the file in ~/.cache/SamRewritten which had 0 bytes and started it again and it downloaded it no problem. 

you really need to check for file integrity (sanity checks) before writing an empty file to disk and then on load just assume the empty file is ok.

**Comment by PaulCombal** [comment]
I know! If you have time on your hands to contribute to the project I can guide you implementing this check. Unfortunately I do not have time anymore to commit myself to it. 

Glad we could solve the issue!
