### ISSUE TITLE
Implement "About" menu / popup

### ISSUE THREAD

**Issue by telans** [PaulCombal/SamRewritten-legacy#21]
Would make the "About" selection functional within the popover menu.

Perhaps something like this? I don't know how to implement it into SamRewritten, however.

![0-Screenshot_20191020_233945](https://user-images.githubusercontent.com/45819748/67271654-7b31f500-f4aa-11e9-9876-41e9c7e9f1ef.png)

**Comment by wgpierce** [comment]
Yeah that looks great! It's not too hard to hook it up. Using glade, give it a signal handler and hook it up similar to how the "Refresh Games" button and main_window act. Also add a delete-event, so the about box doesn't get destroyed on close. If you'd like to, make a pull request with those, and I'll accept it! It'd be a good first core coding contribution :smiley: 

If you don't want to, let me know and can do it instead.

**Comment by telans** [comment]
Well, I'm trying to do it with `gtk_show_about_dialog()` but I'm not getting anywhere. I really should learn the basics...
It'll be good to see what you end up doing, for where I'm going wrong

Here's the glade file with the window: [aboutwindow.patch.txt](https://github.com/PaulCombal/SamRewritten/files/3760385/aboutwindow.patch.txt)

Also needed to shrink the icon to 50%, so here's that: 
![icon](https://user-images.githubusercontent.com/45819748/67361411-192fc900-f558-11e9-80fa-c523d7f3f87c.png)

Thanks

**Comment by wgpierce** [comment]
If you made it in glade, you can just hook up the "About" button to a signal handler on clicked, then plumb that signal handler to call  `gtk_widget_show(GTK_WIDGET(m_about_dialog))` after it's constructed during `MainPickerWindow::MainPickerWindow()` .
