### ISSUE TITLE
Cleanup ideas

### ISSUE THREAD

**Issue by telans** [PaulCombal/SamRewritten-legacy#25]
For cleanup - dev branch

- I think it makes sense to move the steam headers into src/steam/
- ~~Are the libraries inside steam/lib needed? They don't seem to be used for building or running~~
- Rename the glade folder to gui (more 'common' name I suppose)? Maybe remove unused glade files (or nest them into glade/dev for example), but looks like they might be used in future. Or could remove them just from master if the dev branch is staying around
- ~~Rename assets/samrewritten64 to icon_64~~
- ~~Rename assets/icon to icon_256 (maybe generate the other common sizes if wanted or when needed)~~

Just thoughts to make the folders look a tad cleaner, will make a PR if wanted

**Comment by wgpierce** [comment]
> I think it makes sense to move the steam headers into src/steam/

They're not source code we wrote for the project, so I think they're fine there. I'm otherwise ambivalent.

> Are the libraries inside steam/lib needed? They don't seem to be used for building or running
correct, not needed

That's correct, they can be deleted.

I'm ambivalent on the GUI folder change, I think it's fine.

> Rename assets/samrewritten64 to icon_64
> Rename assets/icon to icon_256 (maybe generate the other common sizes if wanted or when needed)

Not sure why these were added to take things out of sync between this repo and the AUR repo :(
The `Icon=samrewritten` line is also different between the two -- whatever is cleanest to bring these back into sync would be good.

**Comment by telans** [comment]
> Not sure why these were added to take things out of sync between this repo and the AUR repo :(
The Icon=samrewritten line is also different between the two -- whatever is cleanest to bring these back into sync would be good.

I think this change, with the one in the PKGBUILD below makes this icon globally available rather than stuck in the /usr/lib/sr directory. Also enables different applications to use the different sizes if available.

`install -Dm644 "${_pkgname}/assets/samrewritten64.png" "${pkgdir}/usr/share/icons/hicolor/64x64/apps/samrewritten.png"`

I'd rather keep it all contained into one directory but if that's where icons are supposed to end up ~~I'll probably change it on the aur side too.~~ Yeah when they get renamed/merged I'll mirror this on the aur

I would still rename them here to icon_64,256

**Comment by wgpierce** [comment]
You're right, that's probably the right way to do it. I'll accept pull requests for steam/lib deletion and icon cleanups. I request review of this issue from @PaulCombal for the others since I'm ambivalent.

**Comment by telans** [comment]
I'll also add onto this, 

Move the g++ / make `obj` directory from the root dir to inside src or package. Or remove them after build

**Comment by wgpierce** [comment]
Again I'm ambivalent, so I'll leave it up to Paul. There is a clean verb in the makefile which removes them. Keeping the object files around is useful for incremental builds.

**Comment by PaulCombal** [comment]
> I'll also add onto this,
> 
> Move the g++ / make `obj` directory from the root dir to inside src or package. Or remove them after build

It all comes down to personnal preference on this one. Personnally I do not think compiled files have their place in a `src` folder, and I don't want them to show up in my editor. Though if you're a C++ veteran and think this is a good idea, I'm open to your arguments. 
Also, it's better not to remove them after a build, like @wgpierce  said.

**Comment by telans** [comment]
> Though if you're a C++ veteran and think this is a good idea

Ha!

**Comment by PaulCombal** [comment]
Please make a new thread for comments for the next release!
