### ISSUE TITLE
Desktop file

### ISSUE THREAD

**Issue by ghost** [PaulCombal/SamRewritten-legacy#31]
I don't know who AUR package maintainer, but this package has a broken `.desktop` file.

Pls add `StartupWMClass=samrewritten` into file for work correctly.

**Comment by telans** [comment]
What's broken with it for you? Works fine for me on arch with kde, it seems StartupWMClass might be a gnome thing?

**Comment by PaulCombal** [comment]
XFCE here and it works fine as is.. If you know what needs to be fixed, feel free to do a pull request into the `dev` branch modifying the file `package/samrewritten.desktop`. Thanks!

**Comment by ghost** [comment]
Probably, the problem is found only in gnome-shell, excuse me.
How it works. Without this parameter gnome duplicate icon.

Information about this [issue](https://askubuntu.com/questions/403766/duplicate-icons-for-manually-created-gnome-launcher-items).

![Screenshot from 2019-11-10 22-49-28](https://user-images.githubusercontent.com/50836710/68549730-84104980-040c-11ea-917c-1ec5f83a9dec.png)
Without parameter:
![Screenshot from 2019-11-10 22-49-35](https://user-images.githubusercontent.com/50836710/68549729-84104980-040c-11ea-8c64-dee7c6800e20.png)
With:
![Screenshot from 2019-11-10 22-50-26](https://user-images.githubusercontent.com/50836710/68549728-84104980-040c-11ea-8851-033aff59c698.png)

**Comment by ghost** [comment]
WMClasses

![Screenshot from 2019-11-10 23-00-21](https://user-images.githubusercontent.com/50836710/68549848-e6b61500-040d-11ea-9f1b-1834cb87bad2.png)

**Comment by PaulCombal** [comment]
PR Merged
