### ISSUE TITLE
error encountered on file read

### ISSUE THREAD

**Issue by PaulCombal** [PaulCombal/SamRewritten-legacy#42]
In SteamAppDAO, fails with Tumbleweed, related

https://www.reddit.com/r/linux_gaming/comments/dyhkkb/steam_achievement_manager_for_linux_gets_an/f84ig8j/

**Comment by wgpierce** [comment]
I just tried it out on tumbleweed and it worked fine.

**Comment by PaulCombal** [comment]
Yeah, but after I finish dealing with gtkMM I'll rewrite the crashing messages to include more info so that I can actually understand what's going on. This issue is just a reminder

**Comment by PaulCombal** [comment]
The issue should be addressed now with detailed error messages, but OP deleted his message so I can't contact him back to investigate further. Weird issue though.
