### ISSUE TITLE
Long achievement descriptions

### ISSUE THREAD

**Issue by pehsa** [PaulCombal/SamRewritten-legacy#47]
I'm just tested the other issue when I found this.

The window size is depend on the content, like Game names or achievement description.

If the game has an achievement with a long description the window width will be long enough to be out of screen.
For example PayDay 2's Wind of Change achievement has a very long description which made the window width to 2701px, which is only usable on ultra wide monitors (or dual monitors).

**Comment by wgpierce** [comment]
This is fixed by above commit.
