### ISSUE TITLE
Cant install on ubuntu

### ISSUE THREAD

**Issue by lloootsop** [PaulCombal/SamRewritten-legacy#55]
Hi, im trying to use that programm, im getting this error when i run with the following command `./build_appimage.sh`
ERROR: Failed to run plugin: appimage

**Comment by lloootsop** [comment]
For more details of error:
[appimage/stderr]       Please set the $VERSION environment variable if this is not intended
[appimage/stderr] Unable to guess the architecture of the AppDir source directory "AppDir"
[appimage/stderr] A valid architecture with the ARCH environmental variable should be provided
[appimage/stderr] e.g. ARCH=x86_64 appimagetool ...
ERROR: Failed to run plugin: appimag

**Comment by lloootsop** [comment]
Also tried to run the launch.sh:
./launch.sh: line 10: /home/khan/SamRewritten/bin/samrewritten: No such file or directory

**Comment by lloootsop** [comment]
![Screenshot from 2020-04-27 22-46-34](https://user-images.githubusercontent.com/61469147/80424110-fd2b2c80-88d8-11ea-8cf9-452b411ca849.png)

**Comment by PaulCombal** [comment]
Hello, 
Thanks for the bug report! Can you tell me the output of `$ cat /etc/lsb-release`? Also did you run the `make` command first and did it work without errors?

Thanks

**Comment by lloootsop** [comment]
I runned the make and i get these errors:
![Screenshot from 2020-04-29 14-04-09](https://user-images.githubusercontent.com/61469147/80599269-987be900-8a22-11ea-8089-b6342269ec4a.png)

**Comment by lloootsop** [comment]
i deleted the samrewrittend and i used `git clone `https://github.com/PaulCombal/SamRewritten.git` again and i runned the `make`command and i got errors, after i tryed to run on the bin file path with the following command `./launch.sh` and it says
![Screenshot from 2020-04-29 14-08-30](https://user-images.githubusercontent.com/61469147/80599500-eee92780-8a22-11ea-8c7f-dcf8a7b7f141.png)

**Comment by lloootsop** [comment]
@PaulCombal 
![Screenshot from 2020-04-29 14-09-12](https://user-images.githubusercontent.com/61469147/80599557-07f1d880-8a23-11ea-9383-371ef27a6204.png)

**Comment by PaulCombal** [comment]
Hello, as stated in the README, Ubuntu is supported from version 19. Please refer to issue #45 or use an AppImage build in the "release" tab. Thank you.

**Comment by Khantanjil** [comment]
Im trying to run this appimage but doesnt open anything
![Screenshot from 2020-04-30 10-39-18](https://user-images.githubusercontent.com/61469147/80696145-e5b59480-8ace-11ea-9338-d6f16dbdcda5.png)

**Comment by Khantanjil** [comment]
Also i runned the chmod a+x

**Comment by wgpierce** [comment]
If you're still on Ubuntu 18.04, the latest master includes commits 082ad7f1182e9a8e3ae9d90d82267b6f33f9b658 and 7358596158221af89b19f89f25d4ee8b4e8ecfb1 to fix these problems and enable building.

**Comment by lloootsop** [comment]
I solved it, thanks
