### ISSUE TITLE
Trying to use this program but cant login

### ISSUE THREAD

**Issue by lloootsop** [PaulCombal/SamRewritten-legacy#56]
Im trying to use this program, but seems like there is an loop when i try to unlock achievements. When i click any game appears the login window and when i try to login, appears again and again
![Screenshot from 2020-04-30 10-52-56](https://user-images.githubusercontent.com/61469147/80697658-3201d400-8ad1-11ea-8744-07edbdd9540a.png)
![Screenshot from 2020-04-30 10-53-30](https://user-images.githubusercontent.com/61469147/80697663-34642e00-8ad1-11ea-99aa-c3fcb6dad5d2.png)

**Comment by wgpierce** [comment]
Seems like more of a Steam problem... SAM just connect to the running Steam instance. Can you try logging out of Steam on all computers including that one, then relaunching Steam on that computer and try again?

**Comment by lloootsop** [comment]
Maybe you are right, i was used another program to farm cards on steam. I will try
