### ISSUE TITLE
Cant install AppImage or compile on Opensuse Leap 15.1

### ISSUE THREAD

**Issue by TECHNOFAB11** [PaulCombal/SamRewritten-legacy#58]
When downloading one of the AppImages i get this error:

```
/tmp/.mount_SamRewFpiRHZ/usr/bin/samrewritten: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_SamRewFpiRHZ/usr/bin/../lib/libgtk-3.so.0)
/tmp/.mount_SamRewFpiRHZ/usr/bin/samrewritten: /lib64/libc.so.6: version `GLIBC_2.27' not found  (required by /tmp/.mount_SamRewFpiRHZ/usr/bin/../lib/libssh.so.4)
```

When compiling via make i get the following: https://pastebin.com/ry4RT9s2
I installed all dependencies i could, more than mentioned too.

**Comment by PaulCombal** [comment]
Hello, is your system up to date? SamRewritten is more likely to work with the newest up-to-date rolling release distributions. Please refer to #45 for your build issue. Can you paste the output of `cat /etc/lsb-release`?

**Comment by TECHNOFAB11** [comment]
Output of the command:
`LSB_VERSION="core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:core-3.2-x86_64:core-4.0-x86_64"`
If you mean having the latest version installed by up to date, then no. I have Opensuse Leap 15.1, but there is 15.2 out. I dont think that will fix it, but i wanted to upgrade either way, so im gonna do that and try again if you dont have any other solution

**Comment by PaulCombal** [comment]
Unfortunately it just seems your distribution comes with older versions of GTK and coreutils, which SamRewritten aren't capable of running with.. Please let me know if this works after the update, that way I can add that version to the README. Thank you!

**Comment by TECHNOFAB11** [comment]
Will do!

**Comment by TECHNOFAB11** [comment]
With Opensuse Leap 15.2 it now works! I could compile it with make and tried it out. So far everything works great, could unlock and lock achievements and it detected all games as far as i can see. Thank you, closing this

**Comment by PaulCombal** [comment]
Thank you for telling me, I'll update the README accordingly!

**Comment by wgpierce** [comment]
Not sure what version of gtkmm Opensuse Leap 15.1 ships, but it may work on the latest master since it includes commits 082ad7f1182e9a8e3ae9d90d82267b6f33f9b658 and 7358596158221af89b19f89f25d4ee8b4e8ecfb1 to enable building on Ubuntu 18.04, gtkmm 3.22.

If someone is on Opensuse Leap 15.1 and wants to test it out, we could update the README if everything compiles fine or see how feasible any WAR is.
