### ISSUE TITLE
Does not run on Ubuntu 16.04

### ISSUE THREAD

**Issue by probonopd** [PaulCombal/SamRewritten-legacy#67]
Hi, thanks for making an AppImage. Unfortunately it does not run on Ubuntu 16.04 because it was built on a too new system:

```
/run/firejail/appimage/.appimage-9237/usr/bin/samrewritten: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /run/firejail/appimage/.appimage-9237/usr/bin/samrewritten)
```

Please see
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages/cc2441518975caca23e9ce2dba6f08a22c678d1e#creating-appimages-that-are-compatible-with-many-systems

Reference:
https://github.com/AppImage/appimage.github.io/pull/2035

**Comment by PaulCombal** [comment]
Hello @probonopd,

What an honour to have a person like you show interest on this small repository!

Anyway, I currently do not plan to put work into supporting older releases of operating systems. I encourage everyone to keep their rolling-release distro updated, or use the most recent LTS desktop release.

However, if you can provide a compatible build, I can certainly add it to the release. The AppImage building instructions can be found on the README.

Thank you for your feedback

**Comment by wgpierce** [comment]
We're aware of the glibc backwards incompatibility that's encountered with AppImages.
  
@probonopd how well does compiling on Ubuntu 16.04 work? If there are too many conflicts, making it work would require recompiling libraries for the older platform, which may have more dependency problems. If it works fine, then we'll add the binaries and update the supported list.

As Paul said, we're open to PRs/instructions to make it work on older platforms or builds that work there, but we don't plan on putting in the work to support older releases of operating systems.

**Comment by probonopd** [comment]
Hi @wgpierce 

> We're aware of the glibc backwards incompatibility that's encountered with AppImages.

This has nothing to do with AppImages. It has to do with how backward compatibility with glibc works. You will get the same result if you put the binaries e.g., into a zip file rather than into an AppImage. Remember that an AppImage is just a self-mounting "disk image" that executes whatever you put inside.

So we recommend to always compile on the oldest still-supported Linux distributions, e.g., for Ubuntu this is currently 16.04.

> We don't plan on putting in the work to support older releases of operating systems.

Won't you lose many potential users this way? I tend to always think the other way around, build for the "lowest common denominator" so that as many users as possible can run an app...

> @probonopd how well does compiling on Ubuntu 16.04 work?

I can't tell for SamRewritten, but in general it works well, especially if a CI (continuous integration) system checks each git submit and gives an error if a developer tries to push something that would break compilation on the target system.

Do you think it would be worthwhile to get e.g., automated builds on Travis CI going?

**Comment by PaulCombal** [comment]
I created SamRewritten with the goal to make it available to people who use the software I know and love. 16.04 is over 4 years old now, and I believe it is your responsability to dist-upgrade to use software released years after your initial OS release. This project isn't commerial in any way, the number of users isn't a metric I'm monitoring.

I don't really have much time to fix and improve everything I want on SamRewritten. CI/CD, a better Makefile, the linking of libraries, nomenclature, fixing the reported issues, snaps & flatpaks, and much more aspects of this projects need to be revamped and I definitely look forward to using the latest technologies available to make things possible.

I won't be working on retrocompatibility, but rather I'll use the latest techs. However I'm still open to merging pull requests aimed at retrocompatibility.

> Do you think it would be worthwhile to get e.g., automated builds on Travis CI going?

This is definitely something I'm looking forward to, using Github actions. As I said, I'll probably try setting this up when I'll have a little bit of time.

**Comment by PaulCombal** [comment]
Closed due to inactivity
