### ISSUE TITLE
Unsubscribed games don't show up.

### ISSUE THREAD

**Issue by wgpierce** [PaulCombal/SamRewritten-legacy#7]
In issue #6 , thymikon mentioned that unsubscribed apps don't show up in SAM. But, they do still count towards Steam completion percentage according to "Rule # 4: The Uninstall & Deactivation Rule" on [How Average Game Completion Rate is Calculated](https://steamcommunity.com/sharedfiles/filedetails/?id=650166273). Filing this issue to investigate how to deal with unsubscribed apps.

**Comment by wgpierce** [comment]
> I think going gibbed's way would not be a bad option, but digging a little bit further I found a few function signatures in OpenSteamworks that can be interesting to look at : [Here](https://github.com/SteamRE/open-steamworks/blob/master/Open%20Steamworks/Steam.h#L197)
> 
> Some guy managed to do so 10 years ago [on this thread](https://forum.facepunch.com/dev/ozhz/Open-Steamworks/5/) (the Voided guy in the middle of the page), do you believe investigating on this is something worth doing?

That would be good to investigate how those behave. Can you try that out? Or if you're busy with other things, I understand.
I'm going to check out whether gibbed's way or the project https://github.com/seiyria/steam-avg-pct-cli with Steam API keys picks them up. I know that completionist.me doesn't pick up on them because I just checked. I'll report back within a few days.

**Comment by PaulCombal** [comment]
Hi, just giving an update

I just created a new playground branch and discovered a lot of interesting things. My tests did not lead to anything at all yet, I work directly in the `/bin` folder.

If you try running:
`$ nm -D --defined-only libsteam.so` you can see that there are a lot of exported functions. I did not manage to use them yet but there's something to learn there.

C/C++ is not my main language, so I thought that if you are more experienced than I am maybe you could eventually find out how things work.

Here is the test main: https://github.com/PaulCombal/SamRewritten/blob/playground_branch/bin/test_main.cpp

I'm gonna be away for a week or so, so I'm not expecting to go much farther on this any time soon.

Regarding the API way, I'm not sure how to feel about it, specially for private profiles.
I'd feel better if the `AppIsOwned` method were used.

**Comment by wgpierce** [comment]
Update on my tests: neither gibbed's way nor steam-avg-pct-cli pick up on unsubscribed apps.
Paul, your test doesn't return anything in the appid array. We would also need to double check that the function is being invoked properly. We can try to match Voided's setup routines as a first step.

For now the best workaround is just to resubscribe to those games if you want to modify their achievements. The section "How to Find Games Your Library Is Missing" in the link to "How Average Game Completion Rate is Calculated" at the top is a way to find these games.

**Comment by PaulCombal** [comment]
I took a break, but I thought a little about this issue. The SteamGetAppIds function is meant to be called from the Steam Client, so that it requires credentials and being logged in, instead of the steam_api calls which just hooks to the current Steam instance.

Regarding unsubscribed apps, I don't believe they should be picked up anyway, but if you believe this must be done you can go ahead.

I believe using isAppOwned is the best implementation I can think of so far, so I think I will do this next time I touch this repo.

**Comment by PaulCombal** [comment]
I added a `beta` branch, which registers all subscribed apps. It would be awesome if you could give me feedback on the new code, because I know it's messy and I probably left commentd out old code. 

I think I will work a little on the interface before merging into master. I believe a search-based tool would make more sense than a list-based tool in this case.

**Comment by wgpierce** [comment]
Hey sorry if I hadn't responded.
I can review that tonight!

I had sent you another email about splitting out the two windows from each
other. I am definitely working on this tonight and will put it in a new
branch.

**Comment by PaulCombal** [comment]
I think the interface needs to be reworked. We both have ideas, I think it would be a good idea to make quick mockups and a list of ideas before doing anything, I'll keep you updated if I think of something!

**Comment by wgpierce** [comment]
gibbed's original SAM and steam-avg-pct-cli don't pick up on apps that are unsubscribed, and we're now using basically the same algorithm as gibbed's SAM, so I don't think this issue is really viable without a lot more hackery. I'll close this issue for now.
