### ISSUE TITLE
Cannot change stats with the AppImage CLI ?

### ISSUE THREAD

**Issue by Krafting** [PaulCombal/SamRewritten-legacy#70]
I might do this wrong but it seems I can't change stats via command line with the appimage:

The command I run:
`./SamRewritten-Ubuntu_18.04-f75eaa9-x86_64.AppImage -a 4000 --statnames GMA_X_MINUTES_STAT --statvalues 3685`

the output: 
`Error opening the Steam Client library. /home/krafting/.steam/steam/linux64/steamclient.so may not exist. Info:
/home/krafting/.steam/steam/linux64/steamclient.so: cannot open shared object file: No such file or directory
Trying alternate Steam Client library path.
[S_API] SteamAPI_Init(): Loaded '/home/krafting/.steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 4000
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198089847935 [API loaded no]
Changing Float stat to value3685.000000 failed`

Doing this via the GUI works normally.

**Comment by wgpierce** [comment]
Added a hack to make it work, please try the latest master.
