### ISSUE TITLE
The app doesn't show some icons

### ISSUE THREAD

**Issue by ghost** [PaulCombal/SamRewritten-legacy#72]
Hello! 
I'm using Fedora. I've compiled your app and it looks like this: 
![image](https://user-images.githubusercontent.com/46493085/85222538-9439cf80-b3c4-11ea-809d-1c2c61bb0e08.png)
Can you see broken image? This is the problem!
And when I click on game I again can see broken image:
![image](https://user-images.githubusercontent.com/46493085/85222551-b92e4280-b3c4-11ea-96b6-e844540558dc.png)
 The problem is that you're trying to load icons from name that system doesn't have! See AppBoxRow.cpp line 20:
   ```new_window_button->set_image_from_icon_name("document-export-symbolic", Gtk::BuiltinIconSize::ICON_SIZE_BUTTON);```
There's no 'document-export-symbolic' in my system (Im using GNOME). Please replace icons. All icon names are described here -- https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html. 
Thanks! 
With love,
r1ddle

**Comment by ghost** [comment]
We have a choice:
1. Use system icons
2. Use cached icons (I mean, icons from file).
Please choose one

**Comment by ghost** [comment]
I've found some icons. And with them the program looks like this: 
![image](https://user-images.githubusercontent.com/46493085/85539773-e4ac6980-b61e-11ea-94df-78bb4cb57086.png)
![image](https://user-images.githubusercontent.com/46493085/85539876-00177480-b61f-11ea-8edb-e9ca13032ff8.png)
What's ur opinion about that?

**Comment by PaulCombal** [comment]
Sorry if I'm not really active during these times. Using an external icon set is a big no-no. If the icons aren't availabe on your platform, there's probably an icon package you're missing. It works on everybody's distribution except yours. I'll try booting a Fedora and messing around to see if I can solve this issue when I'll have more time.

**Comment by ghost** [comment]
Oh, it's only Fedora's problem? I didn't know about that, sorry.

**Comment by wgpierce** [comment]
The icons were chosen using icon names generally available on the developers' systems. No guarantee they're the best choices, I didn't look into the icon standards too closely. If you have some suggestions for more default ones that still look good, feel free to make a PR.

**Comment by ghost** [comment]
> The icons were chosen using icon names generally available on the developers' systems. No guarantee they're the best choices, I didn't look into the icon standards too closely. If you have some suggestions for more default ones that still look good, feel free to make a PR.

I think that these icons are the best (IMO) ones in list of all built-in icons.
https://github.com/PaulCombal/SamRewritten/issues/72#issuecomment-648739270

**Comment by PaulCombal** [comment]
Hi again @r1ddle1 ,
I had time to give this issue a quick look. This has to do with the Gnome desktop icon theme, which has a very scarce icon set. Since this does not only affect Fedora users but any distro with the stock Gnome desktop, I decided to change the icons as you suggested. 
Here is the commit https://github.com/PaulCombal/SamRewritten/commit/14e9c792ae4aa555fa9bb16c4cd8c89cf61a74ab
Let me know if you have further remarks, otherwise feel free to close the issue.

Thanks for your feedback!

**Comment by ghost** [comment]
Ok, now everything works correctly! Thanks for creating such an amazing app!

**Comment by wgpierce** [comment]
Solution is fine by me. Though it needs a fix to StatBoxRow.cpp too.
