### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by ghost** [PaulCombal/SamRewritten-legacy#73]
Oh god, this app is luggy. It uses about 25% of CPU! And I dunno why. It begins to use a lot of CPU when I click on some game to see achievements.

**Comment by PaulCombal** [comment]
I know, this is an issue with GTK3's list boxes. GTK4 is set to provide a solution to this issue. I will have to reimplement the UI when it comes out, but for now all I can do is wait.

**Comment by ghost** [comment]
Okay, thank you

**Comment by wgpierce** [comment]
@r1ddle1 can you provide an example of an app making it lug that badly? It could be downloading hundreds of app icons, but the GUI is still responsive. Should be better than the original SAM and the same or better as some of its forks.

Are list boxes really the culprit to make it lug that badly?

**Comment by ghost** [comment]
Im gonna record a video for ya

**Comment by ghost** [comment]
[2020-06-25 10-50-32.zip](https://github.com/PaulCombal/SamRewritten/files/4829841/2020-06-25.10-50-32.zip)

**Comment by wgpierce** [comment]
Gotcha, I see. Part of the initial load is downloading the icons. After they are downloaded once, SamRewritten caches them, so they don't have to be downloaded again. After that, loading the icons into the GUI is pretty quick.

I observe no load when the program is not being interacted with, but yeah I see up to one core being consumed when scrolling with TF2 active. There are a _lot_ of GUI elements being moved around, so I think such load isn't unreasonable.

If you want, you could try disabling icons and see if that helps. And if so, you could implement an option to disable icons if you like. We had considered adding it, but it wasn't high priority enough.

**Comment by ghost** [comment]
ok, thanks for answer
