### ISSUE TITLE
GUI Error and rename project

### ISSUE THREAD

**Issue by rejexy** [PaulCombal/SamRewritten-legacy#75]
Latest version of SAM has problem with GUI.
![image](https://user-images.githubusercontent.com/60342258/85914695-23256c80-b849-11ea-9969-df7b09003434.png)

What do you think about changing the name of the project? In general I'm used to "rewritten", but at this stage the project may have its name like, NeoSAM (neo vim), SAMium (chromium, codium) or like GOG, SAM Galaxy, in the end just SAM.

**Comment by PaulCombal** [comment]
Hmm that's a weird issue.. are you sure it's not a problem with your settings? Can you tell me what distro and desktop you're using? As of the project name, maybe I'll change it but believe it or not I still have plenty to do before thinking of that seriously haha. Nice name ideas though!

**Comment by rejexy** [comment]
Arch Linux. Gnome-shell.
I installed the package over of the old one, maybe this is the problem.

**Comment by rejexy** [comment]
Well, i tested AppImage, same error.

![image](https://user-images.githubusercontent.com/60342258/85922874-feec7e80-b88e-11ea-93fc-851ebc410713.png)

Also, the menu looks too small.

![image](https://user-images.githubusercontent.com/60342258/85922918-41ae5680-b88f-11ea-82e0-149724dc522b.png)

**Comment by wgpierce** [comment]
I don't see any reason for renaming it. It's not a "new, better" SAM, it's a port/rewrite to Linux.

I think you're missing 🏅 U+1F3C5 emoji in your emoji pack, so it just displays a big blank box. Your "extra info" icons are also broken; master has a fix for that.

**Comment by rejexy** [comment]
> I don't see any reason for renaming it. It's not a "new, better" SAM, it's a port/rewrite to Linux.
> 
> I think you're missing  U+1F3C5 emoji in your emoji pack, so it just displays a big blank box. Your "extra info" icons are also broken; master has a fix for that.

Yes, I think to replace with 🏆 U+1F3C6. 
As for the name, regardless of whether it is rewritten or not, it seems to me that it is not correct to indicate this in the name. Better to transfer to the description.

**Comment by wgpierce** [comment]
> Yes, I think to replace with trophy U+1F3C6.

If that works, then your emoji pack is broken.

> As for the name, regardless of whether it is rewritten or not, it seems to me that it is not correct to indicate this in the name. Better to transfer to the description.

I don't see a problem with it. Especially for something like this which is emphatically not the original SAM.

**Comment by rejexy** [comment]
If someone endorse the name change, we can create a new issue for discussion. I like NeoSAM.

**Comment by wgpierce** [comment]
Original bug has been fixed. Maybe Paul feels differently, but I don't have a strong desire to rename at this time, so closing this issue.
