### ISSUE TITLE
Timed unlocks takes longer than specified

### ISSUE THREAD

**Issue by RNG-Surfer** [PaulCombal/SamRewritten-legacy#82]
Using the appimage in Ubuntu 20.04, when selecting a few achievement to be unlocked over time:
- Amount: 8
- Unit: Hours
- Spacing: Even
- Order: Selection

It takes a lot longer than 8 hours to unlock them all. The time increment seems to add another unit of the initial increment every 2 achievements unlocked, e.g.
- First achievement: 0 mins
- Second achievement: 21 mins later
- Third achievement: 42 mins later
- Fourth achievement: 42 mins later
- Fifth achievement: 62 mins later
- Sixth achievement: 62 mins later
- Seventh achievement: 83 mins later
- ...

**Comment by wgpierce** [comment]
Issue is fixed on master I believe, can you try that?

**Comment by RNG-Surfer** [comment]
Works fine in master thanks!

**Comment by wgpierce** [comment]
I cut a new release with a new AppImage that picks up this fix.
