### ISSUE TITLE
Ban?

### ISSUE THREAD

**Issue by kokorog** [PaulCombal/SamRewritten-legacy#89]
Is it bannable in 2021

**Comment by PaulCombal** [comment]
I've never used achievement managers on VAC-enabled games, and so far I'm in the clear. Even then this should not get you banned if you use it reasonably. 
As a reminder from the README, use this tool at your own risk: we are not responsible for your actions.

**Comment by tryoxiss** [comment]
Steam Achivement manager only edits achivement data, so unless this does something to affect in-game performance on VAC enabled games (which I highly doubt) you should be good :3
