### ISSUE TITLE
Working on Tessa's Linux Mint 19.1 Tessa

### ISSUE THREAD

**Issue by ghost** [PaulCombal/SamRewritten-legacy#9]
Hello, primeperfectly Thank you for your project. It was a hell I have to use a virtual machine with Windows just to use the **SAM (Steam Achievements Manager)**. I tried to install the program more at the beginning I found it very confusing more succeeded. Do you have plans to make a graphical interface of the program? I also noticed that it does not detect some games and I run some risk of **Vac Ban?** Only use in the conquest that I need to play multiplayer or achievements that no longer to catch.

![Sam Rewritten](https://user-images.githubusercontent.com/52839852/61159761-7e910a00-a4d3-11e9-88fa-da102075d497.png)
![Sam Rewritten (2)](https://user-images.githubusercontent.com/52839852/61159764-82bd2780-a4d3-11e9-9ddf-009c75c92b2b.png)

**Comment by PaulCombal** [comment]
Hello, thank you for the feedback!

This project is in a very early stage, and I do not have much time to invest to implement new features quickly. I know a lot of games are not picked up, as pointed in issue https://github.com/PaulCombal/SamRewritten/issues/6 , and once I fixed all the bugs, and filled all the placeholders, I feel like releasing an AppImage build would help with the accessibility.

Right now I can not spend as much time as before on this project, so if you can find contributors for it, that would be very welcome. I will try to participate in it from time to time though.

Regarding VAC, I do not take any responsability over bans, but I do not believe you should get a ban, as you are not logged in a VAC secure server.
Also, why would you set up a VM in windows if you can just use Gibbed's SAM?

**Comment by ghost** [comment]
> Hello, thank you for the feedback!
> 
> This project is in a very early stage, and I do not have much time to invest to implement new features quickly. I know a lot of games are not picked up, as pointed in issue #6 , and once I fixed all the bugs, and filled all the placeholders, I feel like releasing an AppImage build would help with the accessibility.
> 
> Right now I can not spend as much time as before on this project, so if you can find contributors for it, that would be very welcome. I will try to participate in it from time to time though.
> 
> Regarding VAC, I do not take any responsability over bans, but I do not believe you should get a ban, as you are not logged in a VAC secure server.
> Also, why would you set up a VM in windows if you can just use Gibbed's SAM?

It's a shame you do not have so much time to invest in a tool like that. And an incredible project. Well I've set up a VM because SAM does not work on Linux or WINE. It does not work at all, just using Windows or configuring a VM. I was playing The Darkness 2 and Left 4 Dead 2 when I came across an achievement called "Valve Gift Grab 2011 - L4D2 - Collect three gifts dropped by Special Infected in Versus Mode". So I thought how I can get it if it was just released in 2011. I tried several tutorials on YouTube teaching how to get it and nothing worked. So I decided to pass the SAM and I decided to use in conquests of this type, those conquests without foot or head like for example. You have 95% of your progess and the achievement was right at the beginning type, play a note of the piano and you can not go back and you think, seriously? play a note kind, meaningless conquests. More back to the subject ... do not let this project die or stopped, and one of the best projects I've ever seen in relation to linux. I've seen some that did not work out or are very problematic, and your very early stage worked very well. And a person who can help you and Liam from GamingOnLinux (https://www.gamingonlinux.com). And a site aimed at games for Linux. Talk to him and he will disclose your project and so may appear people with interest in helping internally. I would if I could help, but not intending anything programming.

**Comment by wgpierce** [comment]
Hey @Alisonmontteiro , thanks for the positive feedback! The GUI is already implemented and as Paul said, there isn't much risk of VAC bans. I am available to implement features and am working on bringing it up to feature parity with the original SAM when I have time. Paul has reached out on Reddit before to expand the project.
Paul, Alison set up a VM to run Windows to run the original SAM.

@Alisonmontteiro did you have any concrete problems currently? Otherwise I don't think there are any problems in the issue and we can close it.
