### ISSUE TITLE
Doesn't start anymore on Ubuntu 20.04

### ISSUE THREAD

**Issue by everlyy** [PaulCombal/SamRewritten-legacy#91]
Program version: 2.1
OS: Ubuntu 20.04 LTS
Problem: The program isn't starting, so I tried to start it through my terminal and it gave me this output: 
```

(samrewritten:21337): Gtk-WARNING **: 19:42:48.513: Theme parsing error: gtk.css:6325:24: 'none' is not a valid color name

(samrewritten:21337): Gtk-WARNING **: 19:42:48.575: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Numix/16/status/image-missing.svg: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_font_options_get_variations (gdk-pixbuf-error-quark, 5)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Numix/16/status/image-missing.svg: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_font_options_get_variations (gdk-pixbuf-error-quark, 5)
/tmp/.mount_SamRewFVU4eZ/AppRun: line 8: 21337 Aborted                 (core dumped) ${SCRIPT_PATH}/samrewritten $@
```

I've run the program before but when I tried today (I didn't update my program or OS) it didn't start.

**Comment by PaulCombal** [comment]
I can't tell for sure, but it looks like you're missing the cairo library. I can't blame you since this isn't listed as a dependency. Do you have packages starting with `libcairo` installed? If so, which ones (you can check with `apt list --installed | grep libcairo`)?

EDIT: Do you also have `librsvg2-common` installed? That might be what you're missing

**Comment by everlyy** [comment]
So for libcairo, I have 5 packages installed:
```
libcairo-gobject-perl/focal,now 1.005-2 amd64 [installed,automatic]
libcairo-gobject2/focal,now 1.16.0-4ubuntu1 amd64 [installed,automatic]
libcairo-perl/focal,now 1.107-1 amd64 [installed,automatic]
libcairo2/focal,now 1.16.0-4ubuntu1 amd64 [installed,automatic]
libcairomm-1.0-1v5/focal,now 1.12.2-4build1 amd64 [installed,automatic]
```
and for librsvg2-common, I have 1 package installed:
```
librsvg2-common/focal-updates,now 2.48.9-1ubuntu0.20.04.1 amd64 [installed,automatic]
```

Do I need to install specific versions of these?

**Comment by PaulCombal** [comment]
Maybe, but you shouldn't have to.. That's definitely something to fix. Maybe @wgpierce can comment on that..
A quick Google search showed me that users with exotic icon sets/themes can get this error. Do you use stock Ubuntu settings?

**Comment by everlyy** [comment]
That may be it. I downloaded some custom themes. I'll try to run the program with default Ubuntu themes.

EDIT: The program started without issues on all the default themes. I'll try to figure out what theme it specifically is if someone has the same issue and sees this.

EDIT 2: After some trying, I found out it's  the `Numix-Circle` icon pack I use. When I use the default icons, the program starts fine.

**Comment by PaulCombal** [comment]
Glad you found it! I'm not sure if I can do much about it, looks  more like some of the icons cause a crash in dependencies of SamRewritten. That means there's not much I can do about it.. Anyways feel free to close the issue if that's good for you, otherwise your best shot is to report the error to the GTK team or the theme's creator. Thanks for the feedback :+1:

**Comment by everlyy** [comment]
Okay that's fine. Thanks for the quick responses!
