### ISSUE TITLE
(Question + Feature Request?)

### ISSUE THREAD

**Issue by ghost** [PaulCombal/SamRewritten-legacy#93]
Hello, I'm about to move completely onto Linux, and am obviously interested in your program. My question is - is it possible to edit the exact time of getting an achievement (for example, changing it from 14:00 to 15:00)?

**Comment by PaulCombal** [comment]
I'm going through the issue list, and I noticed I missed yours, sorry 😬

To answer your question (if it's not too late) timed unlocking has been implemented, which means you can just leave Samrewritten open and the achievements will be unlocked after the selected time. You can also relock, and unlock achievements again to change the time it has been unlocked.

Other than that, I am not aware of a way to edit the unlocking date directly.

Is that what you wanted to know?

Again, I know it's awkward answering after half a year haha
