### ISSUE TITLE
Error opening with Linux Mint icon (When will a next update come out?)

### ISSUE THREAD

**Issue by ghost** [PaulCombal/SamRewritten-legacy#94]
When exactly will there be an update? Any plans to launch in flatpak?

The program after some updates does not open anymore with the Linux Mint (Mint-Y) icons and the following error
```
****(samrewritten:10806): Gtk-WARNING **:** 10:42:42.290: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
**Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Mint-Y/actions/16/image-missing.svg: The image loading module could not be loaded:/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_font_options_get_variations (gdk-pixbuf-error-quark, 5)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Mint-Y/actions/16/image-missing.svg: The image loading module could not be loaded:/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_font_options_get_variations (gdk-pixbuf-error-quark, 5)
/tmp/.mount_SamRewaEsoPE/AppRun, linha 8: 10806 Aborted                (core image recorded) ${SCRIPT_PATH}/samrewritten $@****
```

**Comment by PaulCombal** [comment]
Hello,
I'm fairly sure this is a duplicate of #91 . Can you please confirm this?

As for the next update, I don't know. I have many ideas for this project but very little time for myself. I would be thrilled to have new contributors come and update it from time to time but this isn't the case sadly. I'd say if you want more updates, the best you can do is spread the word about this project, and bring in new contributors!

Thanks!

**Comment by ghost** [comment]
I'm sorry, I didn't really realize it was duplicated. Well, I'm not a developer (unfortunately) but I design it. You could try a partnership with these guys, Boiling Steam, Gaming on linux and Phoronix who are specialized in content about linux, games. They could help you a lot with disclosure. And feel free to lock up my topic and thank you very much for your answer. Your program works much better than the Windows version.

**Comment by PaulCombal** [comment]
No problem, feel free to ask anything or submit ideas, they're always welcome! As for your suggestion, maybe I'll try to reach them if I have some spare time. I'm both happy and surprised that it works well for you, as I know there are still many fixes to bring to SamRewritten. See you!
