### ISSUE TITLE
Unable to find your Steam installation directory.. Please report this on Github!

### ISSUE THREAD

**Issue by uvql** [PaulCombal/SamRewritten-legacy#95]
**OS:**
Pop!_OS 20.10

**Steps**
1. Run `./SamRewritten/bin/launch.sh`
2. Return `Unable to find your Steam installation directory.. Please report this on Github!`

**Comment by PaulCombal** [comment]
Can you please tell me how you installed Steam (package manager, snap..)? Note that so far only the package manager install is supported. Do you know where your "appcache" folder is located (eg: ~/.steam/appcache/, ~/.steam/steam/appcache/)? 

Thanks for the info, pleaase tell me if you still struggle!

**Comment by uvql** [comment]
Thanks for the reply!

In Pop!_OS, there is a Pop!_Shop and I download Steam from there. The appcache is located at `~/.var/app/com.valvesoftware.Steam/.steam/steam/appcache`.

**Comment by uvql** [comment]
I read #1 and tried to modify the MySteam.cpp file. In line 54, I added
```
else if (file_exists(home_path + "/.var/app/com.valvesoftware.Steam/.steam/steam/appcache/appinfo.vdf")) {
        m_steam_install_dir = std::string(home_path + "/.var/app/com.valvesoftware.Steam/.steam/steam");
        return;
    } 
```
However the error is still here. Maybe I am missing something?

**Comment by vchernin** [comment]
It looks like you have installed the steam flatpak (inferred based on what directory your files are in).

Are you trying to open a steam game that uses the steam runtime via the command line? I believe that may be the issue, since directories are different with a flatpak, and the steam flatpak is not yet considered "feature complete" compared to traditional packages.

I'd suggest going to the pop shop and ensuring you install the deb file and not the flatpak for this use case.

**Comment by uvql** [comment]
You are right! I have reinstall the deb version of steam and I can use the SamRewritten now. Many thanks!

**Comment by PaulCombal** [comment]
No worries! Thanks to everyone helping. @uvql do you feel like this is something I should add to the README?

**Comment by vchernin** [comment]
I’d say this is something that should defintely be in the README. It is very relevant and necessary for the growing number of steam flatpak users.

I would also suggest opening a bug for this specific issue on the [steam flatpak github](https://github.com/flathub/com.valvesoftware.Steam/issues). I do however imagine it’s not an issue with flatpak itself, but a problem that requires having specific instructions for steam flatpak users. A flatpak specific fix for the README could resemble how [mangohud](https://github.com/flightlessmango/MangoHud) has different instructions for traditional installation and flatpak installation.

**Comment by PaulCombal** [comment]
Thanks for the info! I'll add Flatpak support to the TODO list (in case this gets updated), and I'll add a note on the README about that. If that's ok with you I will close the issue
