### ISSUE TITLE
Latest AppImage fails on Ubuntu 21.04

### ISSUE THREAD

**Issue by timvisee** [PaulCombal/SamRewritten-legacy#96]
The latest AppImage provided with the latest release fails to launch due to an incorrect shared object path.

The current master fixed this and runs fine.

Are there any plans for a new release including an AppImage?

**Comment by PaulCombal** [comment]
Thanks for the report. Do you have any logs? When you say it works on master, did you compile it yourself? In what format?

**Comment by timvisee** [comment]
I've already removed it, but I'll give it a retry soon and post logs.

Yes, I compiled the latest version from master myself, which works fine. Not sure what you mean with what format, but I've `make`d and ran it with the accompanied script in `bin/`.

**Comment by timvisee** [comment]
When running the AppImage, I get the following output: 

```bash
$ ./SamRewritten-Ubuntu_18.04--d29ad13-x86_64.AppImage
Error opening the Steam Client library. /home/timvisee/.steam/steam/linux64/steamclient.so may not exist. Info:
/home/timvisee/.steam/steam/linux64/steamclient.so: cannot open shared object file: No such file or directory
Trying alternate Steam Client library path.
Gtk-Message: 14:24:31.323: Failed to load module "colorreload-gtk-module"

(samrewritten:277254): Gtk-WARNING **: 14:24:31.407: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/breeze-dark/status/16/image-missing.svg: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_font_options_get_variations (gdk-pixbuf-error-quark, 5)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/breeze-dark/status/16/image-missing.svg: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_font_options_get_variations (gdk-pixbuf-error-quark, 5)
/tmp/.mount_SamRewkXmA6M/AppRun: line 8: 277254 Aborted                 (core dumped) ${SCRIPT_PATH}/samrewritten $@
```

It looks like it can't find `steamclient.so`, which it tries to access here: `/home/timvisee/.steam/steam/linux64/steamclient.so`

Based on the following command, it looks like my shared object is located in `~/.steam/linux64/steamclient.so` instead of `~/.steam/steam/linux64/steamclient.so`:

```bash
$ locate steamclient.so | grep linux64
/home/timvisee/.steam/linux64/steamclient.so
```

Again: this issue doesn't show up when `make`ing the latest `master`, and running `./bin/launch.sh`.

**Comment by PaulCombal** [comment]
Can you confirm it is not a duplicate of #94 and #91 ? In this case if you can provide your AppImage build on Ubuntu I will pin it on the release tab.

**Comment by timvisee** [comment]
It appears you are right.

I just noticed that the same shared object error came up with the newly compiled build. I initially thought the GTK errors after it (in the log above) was just additional noise.

Sorry for not noticing this earlier.
